<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-01-27T14:07:06 IST" name="Suite" finished-at="2024-01-27T14:07:44 IST" duration-ms="38377">
    <groups>
    </groups>
    <test started-at="2024-01-27T14:07:06 IST" name="Test" finished-at="2024-01-27T14:07:44 IST" duration-ms="38377">
      <class name="App_login_test.login_test_using_selenium">
        <test-method signature="login_using_selenium()[pri:0, instance:App_login_test.login_test_using_selenium@794cb805]" started-at="2024-01-27T14:07:06 IST" name="login_using_selenium" finished-at="2024-01-27T14:07:44 IST" duration-ms="38261" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Forgotten Password | Can't Log In | Facebook> but was:<Facebook>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Forgotten Password | Can't Log In | Facebook> but was:<Facebook>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:125)
at App_login_test.login_test_using_selenium.login_using_selenium(login_test_using_selenium.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_using_selenium -->
      </class> <!-- App_login_test.login_test_using_selenium -->
      <class name="App_login_test.login_test">
        <test-method signature="login_test1()[pri:0, instance:App_login_test.login_test@5cee5251]" started-at="2024-01-27T14:07:44 IST" name="login_test1" finished-at="2024-01-27T14:07:44 IST" duration-ms="27" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_test1 -->
        <test-method signature="login_test2()[pri:0, instance:App_login_test.login_test@5cee5251]" started-at="2024-01-27T14:07:44 IST" name="login_test2" finished-at="2024-01-27T14:07:44 IST" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_test2 -->
        <test-method signature="login_test3()[pri:0, instance:App_login_test.login_test@5cee5251]" started-at="2024-01-27T14:07:44 IST" name="login_test3" finished-at="2024-01-27T14:07:44 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_test3 -->
      </class> <!-- App_login_test.login_test -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
